/**
 * Nationality options for the Primary Passenger form.
 * Kenya first (default — most riders are Kenyan), then the rest of the world
 * grouped by region, then an explicit "Other" escape hatch. Values are the
 * nationality adjectives passengers actually write on manifests.
 */

export const OTHER_NATIONALITY = "Other";

export const NATIONALITY_GROUPS: { group: string; options: string[] }[] = [
  {
    group: "East Africa",
    options: [
      "Kenyan",
      "Ugandan",
      "Tanzanian",
      "Rwandan",
      "Burundian",
      "South Sudanese",
      "Ethiopian",
      "Somali",
      "Eritrean",
      "Djiboutian",
    ],
  },
  {
    group: "Africa",
    options: [
      "Egyptian",
      "Libyan",
      "Sudanese",
      "Moroccan",
      "Tunisian",
      "Algerian",
      "Nigerian",
      "Ghanaian",
      "Senegalese",
      "Ivorian",
      "Malian",
      "Burkinabé",
      "Guinean",
      "Sierra Leonean",
      "Liberian",
      "Togolese",
      "Beninese",
      "Nigerien",
      "Chadian",
      "Cameroonian",
      "Central African",
      "Gabonese",
      "Congolese",
      "DR Congolese",
      "Angolan",
      "Zambian",
      "Zimbabwean",
      "Mozambican",
      "Malawian",
      "Motswana",
      "Namibian",
      "South African",
      "Lesotho",
      "Swazi",
      "Mauritian",
      "Seychellois",
      "Comoran",
      "Madagascan",
      "Cape Verdean",
      "Equatorial Guinean",
      "São Toméan",
      "Gambian",
    ],
  },
  {
    group: "Europe",
    options: [
      "British",
      "Irish",
      "French",
      "German",
      "Dutch",
      "Belgian",
      "Spanish",
      "Portuguese",
      "Italian",
      "Greek",
      "Austrian",
      "Swiss",
      "Swedish",
      "Norwegian",
      "Danish",
      "Finnish",
      "Icelandic",
      "Polish",
      "Czech",
      "Slovak",
      "Hungarian",
      "Romanian",
      "Bulgarian",
      "Serbian",
      "Croatian",
      "Slovenian",
      "Bosnian",
      "Albanian",
      "North Macedonian",
      "Montenegrin",
      "Ukrainian",
      "Belarusian",
      "Russian",
      "Lithuanian",
      "Latvian",
      "Estonian",
      "Moldovan",
      "Georgian",
      "Armenian",
      "Azerbaijani",
      "Turkish",
      "Cypriot",
      "Maltese",
      "Monégasque",
    ],
  },
  {
    group: "Americas",
    options: [
      "American",
      "Canadian",
      "Mexican",
      "Brazilian",
      "Argentinian",
      "Chilean",
      "Colombian",
      "Peruvian",
      "Venezuelan",
      "Ecuadorian",
      "Bolivian",
      "Paraguayan",
      "Uruguayan",
      "Guyanese",
      "Surinamese",
      "Costa Rican",
      "Panamanian",
      "Guatemalan",
      "Honduran",
      "Salvadoran",
      "Nicaraguan",
      "Belizean",
      "Cuban",
      "Jamaican",
      "Haitian",
      "Dominican",
      "Barbadian",
      "Trinidadian",
    ],
  },
  {
    group: "Asia & Middle East",
    options: [
      "Chinese",
      "Indian",
      "Japanese",
      "South Korean",
      "North Korean",
      "Mongolian",
      "Taiwanese",
      "Hong Konger",
      "Filipino",
      "Vietnamese",
      "Thai",
      "Cambodian",
      "Laotian",
      "Burmese",
      "Malaysian",
      "Singaporean",
      "Indonesian",
      "Bruneian",
      "Pakistani",
      "Bangladeshi",
      "Sri Lankan",
      "Nepalese",
      "Bhutanese",
      "Maldivian",
      "Afghan",
      "Iranian",
      "Iraqi",
      "Syrian",
      "Lebanese",
      "Jordanian",
      "Israeli",
      "Palestinian",
      "Saudi",
      "Emirati",
      "Qatari",
      "Kuwaiti",
      "Bahraini",
      "Omani",
      "Yemeni",
      "Kazakh",
      "Uzbek",
      "Turkmen",
      "Kyrgyz",
      "Tajik",
    ],
  },
  {
    group: "Oceania",
    options: [
      "Australian",
      "New Zealander",
      "Fijian",
      "Papua New Guinean",
      "Samoan",
      "Tongan",
      "Vanuatuan",
      "Solomon Islander",
    ],
  },
  {
    group: "Other",
    options: [OTHER_NATIONALITY],
  },
];

/** Flat ordered list — Kenya first, then every other option. */
export const NATIONALITIES: string[] = NATIONALITY_GROUPS.flatMap(
  (g) => g.options
);

export const DEFAULT_NATIONALITY = "Kenyan";

export function isValidNationality(value: string): boolean {
  return NATIONALITIES.includes(value);
}
