/**
 * Nationality options for the Primary Passenger form — one alphabetical
 * list (A→Z). "Kenyan" remains the form's default selection, it just sits
 * in alphabetical position now. "Other" is pinned at the end as the escape
 * hatch, not a nationality.
 */

export const OTHER_NATIONALITY = "Other";

export const DEFAULT_NATIONALITY = "Kenyan";

// Source list — regional comments are for maintainers only; the exported
// list below is flat and sorted alphabetically at module load.
const SOURCE: string[] = [
  // East Africa
  "Kenyan",
  "Ugandan",
  "Tanzanian",
  "Rwandan",
  "Burundian",
  "South Sudanese",
  "Ethiopian",
  "Somali",
  "Eritrean",
  "Djiboutian",
  // Africa
  "Egyptian",
  "Libyan",
  "Sudanese",
  "Moroccan",
  "Tunisian",
  "Algerian",
  "Nigerian",
  "Ghanaian",
  "Senegalese",
  "Ivorian",
  "Malian",
  "Burkinabé",
  "Guinean",
  "Sierra Leonean",
  "Liberian",
  "Togolese",
  "Beninese",
  "Nigerien",
  "Chadian",
  "Cameroonian",
  "Central African",
  "Gabonese",
  "Congolese",
  "DR Congolese",
  "Angolan",
  "Zambian",
  "Zimbabwean",
  "Mozambican",
  "Malawian",
  "Motswana",
  "Namibian",
  "South African",
  "Basotho",
  "Swazi",
  "Mauritian",
  "Seychellois",
  "Comoran",
  "Madagascan",
  "Cape Verdean",
  "Equatorial Guinean",
  "São Toméan",
  "Gambian",
  // Europe
  "British",
  "Irish",
  "French",
  "German",
  "Dutch",
  "Belgian",
  "Spanish",
  "Portuguese",
  "Italian",
  "Greek",
  "Austrian",
  "Swiss",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Icelandic",
  "Polish",
  "Czech",
  "Slovak",
  "Hungarian",
  "Romanian",
  "Bulgarian",
  "Serbian",
  "Croatian",
  "Slovenian",
  "Bosnian",
  "Albanian",
  "North Macedonian",
  "Montenegrin",
  "Ukrainian",
  "Belarusian",
  "Russian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Moldovan",
  "Georgian",
  "Armenian",
  "Azerbaijani",
  "Turkish",
  "Cypriot",
  "Maltese",
  "Monégasque",
  // Americas
  "American",
  "Canadian",
  "Mexican",
  "Brazilian",
  "Argentinian",
  "Chilean",
  "Colombian",
  "Peruvian",
  "Venezuelan",
  "Ecuadorian",
  "Bolivian",
  "Paraguayan",
  "Uruguayan",
  "Guyanese",
  "Surinamese",
  "Costa Rican",
  "Panamanian",
  "Guatemalan",
  "Honduran",
  "Salvadoran",
  "Nicaraguan",
  "Belizean",
  "Cuban",
  "Jamaican",
  "Haitian",
  "Dominican",
  "Barbadian",
  "Trinidadian",
  // Asia & Middle East
  "Chinese",
  "Indian",
  "Japanese",
  "South Korean",
  "North Korean",
  "Mongolian",
  "Taiwanese",
  "Hong Konger",
  "Filipino",
  "Vietnamese",
  "Thai",
  "Cambodian",
  "Laotian",
  "Burmese",
  "Malaysian",
  "Singaporean",
  "Indonesian",
  "Bruneian",
  "Pakistani",
  "Bangladeshi",
  "Sri Lankan",
  "Nepalese",
  "Bhutanese",
  "Maldivian",
  "Afghan",
  "Iranian",
  "Iraqi",
  "Syrian",
  "Lebanese",
  "Jordanian",
  "Israeli",
  "Palestinian",
  "Saudi",
  "Emirati",
  "Qatari",
  "Kuwaiti",
  "Bahraini",
  "Omani",
  "Yemeni",
  "Kazakh",
  "Uzbek",
  "Turkmen",
  "Kyrgyz",
  "Tajik",
  // Oceania
  "Australian",
  "New Zealander",
  "Fijian",
  "Papua New Guinean",
  "Samoan",
  "Tongan",
  "Vanuatuan",
  "Solomon Islander",
];

/** Flat, deduplicated, alphabetically sorted (A→Z), "Other" pinned last. */
export const NATIONALITIES: string[] = (() => {
  const unique = Array.from(new Set(SOURCE.filter((n) => n !== OTHER_NATIONALITY)));
  unique.sort((a, b) => a.localeCompare(b, "en"));
  return [...unique, OTHER_NATIONALITY];
})();

export function isValidNationality(value: string): boolean {
  return NATIONALITIES.includes(value);
}
