"""
SGR Feeder Platform — Architecture & Data Model Specification (Body PDF)
=======================================================================
ReportLab body PDF. Cover is generated separately via Playwright (html2poster.js)
and merged via pypdf in the orchestration script.
"""
import os
import sys
import hashlib
import platform
from io import BytesIO

# Skill path setup
PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
_scripts = os.path.join(PDF_SKILL_DIR, "scripts")
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, inch
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, KeepTogether,
    Table, TableStyle, Preformatted, Image, Flowable, HRFlowable, ListFlowable, ListItem,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfgen import canvas as canvas_module

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 1.  FONT REGISTRATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

FONT_DIR = '/usr/share/fonts'

pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans-Bold', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono-Bold.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))

registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans-Bold')

try:
    from pdf import install_font_fallback
    install_font_fallback()
except Exception:
    pass

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 2.  PALETTE (auto-generated by palette.cascade)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PAGE_BG       = colors.HexColor('#f7f7f6')
SECTION_BG    = colors.HexColor('#eeeeec')
CARD_BG       = colors.HexColor('#ebe9e5')
TABLE_STRIPE  = colors.HexColor('#f2f2f0')
HEADER_FILL   = colors.HexColor('#63593b')
COVER_BLOCK   = colors.HexColor('#5a533e')
BORDER        = colors.HexColor('#d3cdb8')
ICON          = colors.HexColor('#9f8c52')
ACCENT        = colors.HexColor('#907422')
ACCENT_2      = colors.HexColor('#3c94b1')
TEXT_PRIMARY  = colors.HexColor('#1b1a18')
TEXT_MUTED    = colors.HexColor('#78756f')
SEM_SUCCESS   = colors.HexColor('#518f66')
SEM_WARNING   = colors.HexColor('#a0844b')
SEM_ERROR     = colors.HexColor('#9c544d')
SEM_INFO      = colors.HexColor('#416990')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 3.  STYLES
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PAGE_W, PAGE_H = A4
LEFT_M = RIGHT_M = 22 * mm
TOP_M = BOTTOM_M = 22 * mm
CONTENT_W = PAGE_W - LEFT_M - RIGHT_M

h1_style = ParagraphStyle(
    name='H1', fontName='FreeSerif-Bold', fontSize=20, leading=26,
    textColor=HEADER_FILL, spaceBefore=24, spaceAfter=14, alignment=TA_LEFT,
)
h2_style = ParagraphStyle(
    name='H2', fontName='FreeSerif-Bold', fontSize=15, leading=21,
    textColor=TEXT_PRIMARY, spaceBefore=16, spaceAfter=8, alignment=TA_LEFT,
)
h3_style = ParagraphStyle(
    name='H3', fontName='FreeSerif-Bold', fontSize=12, leading=17,
    textColor=ACCENT, spaceBefore=12, spaceAfter=6, alignment=TA_LEFT,
)
body_style = ParagraphStyle(
    name='Body', fontName='FreeSerif', fontSize=10.5, leading=16,
    textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=8, alignment=TA_JUSTIFY,
)
body_left_style = ParagraphStyle(
    name='BodyLeft', parent=body_style, alignment=TA_LEFT,
)
muted_style = ParagraphStyle(
    name='Muted', fontName='FreeSerif-Italic', fontSize=9.5, leading=14,
    textColor=TEXT_MUTED, spaceBefore=0, spaceAfter=6, alignment=TA_LEFT,
)
bullet_style = ParagraphStyle(
    name='Bullet', fontName='FreeSerif', fontSize=10.5, leading=15,
    textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=4, alignment=TA_LEFT,
    leftIndent=14, bulletIndent=2,
)
code_style = ParagraphStyle(
    name='Code', fontName='DejaVuSans', fontSize=7.5, leading=10,
    textColor=TEXT_PRIMARY, spaceBefore=4, spaceAfter=4, alignment=TA_LEFT,
    leftIndent=4, rightIndent=4, backColor=CARD_BG, borderColor=BORDER,
    borderWidth=0.5, borderPadding=6,
)
caption_style = ParagraphStyle(
    name='Caption', fontName='FreeSerif-Italic', fontSize=9, leading=12,
    textColor=TEXT_MUTED, spaceBefore=4, spaceAfter=12, alignment=TA_CENTER,
)
toc_l0 = ParagraphStyle(
    name='TOC0', fontName='FreeSerif-Bold', fontSize=11, leading=18,
    textColor=TEXT_PRIMARY, leftIndent=0, spaceBefore=4, spaceAfter=2,
)
toc_l1 = ParagraphStyle(
    name='TOC1', fontName='FreeSerif', fontSize=10, leading=15,
    textColor=TEXT_MUTED, leftIndent=14, spaceBefore=0, spaceAfter=2,
)
callout_style = ParagraphStyle(
    name='Callout', fontName='FreeSerif', fontSize=10, leading=15,
    textColor=TEXT_PRIMARY, spaceBefore=4, spaceAfter=4, alignment=TA_LEFT,
    leftIndent=10, rightIndent=10, backColor=SECTION_BG, borderColor=ACCENT,
    borderWidth=0, borderPadding=8,
)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 4.  HELPERS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

MAX_KEEP_HEIGHT = A4[1] * 0.4

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        try:
            w, h = el.wrap(CONTENT_W, A4[1])
            total_h += h
        except Exception:
            pass
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    else:
        return list(elements)


_heading_counter = [0]
def _next_heading_id():
    _heading_counter[0] += 1
    return f'h_{_heading_counter[0]:04d}'


def H1(text):
    key = _next_heading_id()
    p = Paragraph(f'<a name="{key}"/>{text}', h1_style)
    p.bookmark_name = key
    p.bookmark_level = 0
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def H2(text):
    key = _next_heading_id()
    p = Paragraph(f'<a name="{key}"/>{text}', h2_style)
    p.bookmark_name = key
    p.bookmark_level = 1
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def H3(text):
    return Paragraph(text, h3_style)


def P(text, style=None):
    return Paragraph(text, style or body_style)


def PL(text):
    return Paragraph(text, body_left_style)


def Muted(text):
    return Paragraph(text, muted_style)


def Bullets(items):
    flowables = []
    for item in items:
        flowables.append(Paragraph(f'\u2022\u00a0\u00a0{item}', bullet_style))
    return flowables


def Code(text, caption=None):
    pre = Preformatted(text, code_style)
    elements = [pre]
    if caption:
        elements.append(Paragraph(caption, caption_style))
    return elements


def Callout(text, kind='info'):
    color_map = {
        'info': SEM_INFO,
        'warning': SEM_WARNING,
        'success': SEM_SUCCESS,
        'error': SEM_ERROR,
    }
    border_color = color_map.get(kind, SEM_INFO)
    callout_local = ParagraphStyle(
        name='CalloutLocal', parent=callout_style,
        borderColor=border_color, borderWidth=0,
        backColor=SECTION_BG, borderPadding=8,
    )
    return Paragraph(text, callout_local)


def Table2(headers, rows, col_widths=None, caption=None):
    if col_widths is None:
        n = len(headers)
        col_widths = [CONTENT_W / n] * n

    cell_style = ParagraphStyle(
        name='Cell', fontName='FreeSerif', fontSize=9, leading=12,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    )
    header_cell_style = ParagraphStyle(
        name='HeaderCell', fontName='FreeSerif-Bold', fontSize=9, leading=12,
        textColor=colors.white, alignment=TA_LEFT,
    )

    data = [[Paragraph(str(h), header_cell_style) for h in headers]]
    for row in rows:
        data.append([Paragraph(str(c), cell_style) for c in row])

    t = Table(data, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('FONTNAME', (0, 0), (-1, 0), 'FreeSerif-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 1), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LINEBELOW', (0, 0), (-1, 0), 0.5, BORDER),
        ('LINEBELOW', (0, -1), (-1, -1), 0.5, BORDER),
    ]
    for i in range(1, len(data)):
        if i % 2 == 1:
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_ODD))
        else:
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style_cmds))

    elements = [Spacer(1, 6), t]
    if caption:
        elements.append(Paragraph(caption, caption_style))
    else:
        elements.append(Spacer(1, 12))
    return elements


def HR():
    return HRFlowable(width='100%', thickness=0.4, color=BORDER, spaceBefore=6, spaceAfter=6)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 5.  TOC DOC TEMPLATE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 6.  PAGE DECORATION (header + footer + page numbers)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _page_decoration(canv, doc):
    canv.saveState()
    canv.setStrokeColor(BORDER)
    canv.setLineWidth(0.4)
    canv.line(LEFT_M, 16 * mm, PAGE_W - RIGHT_M, 16 * mm)
    canv.setFont('FreeSerif', 8)
    canv.setFillColor(TEXT_MUTED)
    canv.drawString(LEFT_M, 11 * mm, 'SGR Feeder Platform — Architecture & Data Model Specification')
    canv.drawRightString(PAGE_W - RIGHT_M, 11 * mm, f'Page {doc.page}')
    canv.setStrokeColor(BORDER)
    canv.setLineWidth(0.3)
    canv.line(LEFT_M, PAGE_H - 14 * mm, PAGE_W - RIGHT_M, PAGE_H - 14 * mm)
    canv.setFont('FreeSerif-Italic', 8)
    canv.setFillColor(TEXT_MUTED)
    canv.drawString(LEFT_M, PAGE_H - 11 * mm, 'v1.0  ·  Engineering Reference')
    canv.drawRightString(PAGE_W - RIGHT_M, PAGE_H - 11 * mm, 'August 2026')
    canv.restoreState()
